FROM alpine:3.23.5 AS nginx_landing

RUN apk add --no-cache nginx && mkdir -p /var/www/

ADD ./html.tar /var/www/

COPY ./mysite.conf /etc/nginx/http.d/

ENTRYPOINT ["nginx", "-g", "daemon off;"]

EXPOSE 80
