Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "vagrant-test"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2

    vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]

    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
    
    vb.customize ["modifyvm", :id, "--vram", "128"]
  end


  config.vm.network "forwarded_port", guest: 80, host: 8080
 
  config.vm.disk :disk, size: "1GB", name: "extra1"
  config.vm.disk :disk, size: "1GB", name: "extra2"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
    echo "<h1>Hello from Vagrant</h1>" > /var/www/html/index.html


    DISKS=($(lsblk -dno NAME,SIZE,MOUNTPOINT | \
    awk '$2=="1G" && $3=="" {print "/dev/"$1}' | sort))

    # 2. Форматируем в ext4 (идемпотентно — проверяем blkid)
    for D in "${DISKS[@]}"; do
        if ! blkid "$D" >/dev/null 2>&1; then
            mkfs.ext4 -F "$D"
        fi
    done

    # 3. Точки монтирования
    mkdir -p /mnt/disk1 /mnt/disk2

    # 4. Запись в fstab по UUID
    UUID1=$(blkid -s UUID -o value "${DISKS[0]}")
    UUID2=$(blkid -s UUID -o value "${DISKS[1]}")
    grep -q "$UUID1" /etc/fstab || \
        echo "UUID=$UUID1 /mnt/disk1 ext4 defaults 0 2" >> /etc/fstab
    grep -q "$UUID2" /etc/fstab || \
        echo "UUID=$UUID2 /mnt/disk2 ext4 defaults 0 2" >> /etc/fstab

    # 5. Монтируем по fstab
    mount -a

  SHELL
end
