MACHINES = {
  :server => {
    :box_name => "bento/ubuntu-22.04",
    :vm_name => "server",
    :ip => "192.168.56.10"
  },

  :client => {
    :box_name => "bento/ubuntu-22.04",
    :vm_name => "client",
    :ip => "192.168.56.20"
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.hostname = boxconfig[:vm_name]
      box.vm.network "private_network",
        ip: boxconfig[:ip]

      box.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y openvpn iperf3 selinux-utils

        mkdir -p /root/.ssh
        cp /home/vagrant/.ssh/auth* /root/.ssh/

        setenforce 0 || true
      SHELL

      if boxconfig[:vm_name] == "client"
        box.vm.provision "ansible" do |ansible|
          ansible.playbook = "ansible/provision.yml"
          ansible.inventory_path = "ansible/hosts"
          ansible.host_key_checking = false
          ansible.limit = "all"
        end
      end

    end
  end
end