---

- name: Перечитать конфиг auditd
  ansible.builtin.command: augenrules --load
  changed_when: false

- name: Перезагрузить rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
