[options]
        UseSyslog
        Interface = eth1 

[SSH]
        sequence      = 8881:tcp,7777:tcp,9991:tcp
        seq_timeout   = 5
        tcpflags      = syn
        start_command = /sbin/iptables -I INPUT -s %IP% -p tcp --dport 22 -j ACCEPT
        cmd_timeout   = 60
        stop_command  = /sbin/iptables -D INPUT -s %IP% -p tcp --dport 22 -j ACCEPT

#[options]
#       UseSyslog
#
#[openSSH]
#       sequence    = 7000,8000,9000
#       seq_timeout = 5
#       command     = /sbin/iptables -A INPUT -s %IP% -p tcp --dport 22 -j ACCEPT
#       tcpflags    = syn
#
#[closeSSH]
#       sequence    = 9000,8000,7000
#       seq_timeout = 5
#       command     = /sbin/iptables -D INPUT -s %IP% -p tcp --dport 22 -j ACCEPT
#       tcpflags    = syn
#
#[openHTTPS]
#       sequence    = 12345,54321,24680,13579
#       seq_timeout = 5
#       command     = /usr/local/sbin/knock_add -i -c INPUT -p tcp -d 443 -f %IP%
#       tcpflags    = syn
