# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
    :box_name => "generic/ubuntu2204",
    :vm_name  => "nginx",
    :net => [
      {
        ip: "192.168.11.150",
        netmask: "255.255.255.0",
        network: "mynet"
      }
    ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.hostname = boxconfig[:vm_name]

      box.vm.provider "libvirt" do |lv|
        lv.memory = 768
        lv.cpus = 1
      end

      # NAT сеть (первая сеть создаётся автоматически)

      # Дополнительные сети
      boxconfig[:net].each do |net|
        box.vm.network :private_network,
          ip: net[:ip],
          libvirt__network_name: net[:network],
          libvirt__dhcp_enabled: false,
          auto_config: true
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p /root/.ssh
        cp /home/vagrant/.ssh/authorized_keys /root/.ssh/
        chmod 600 /root/.ssh/authorized_keys

        sed -i 's/#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart ssh
      SHELL

    end
  end
end