Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04" 
  config.vm.define "server" do |server| 
    server.vm.hostname = "server.loc" 
    server.vm.network "private_network", ip: "192.168.56.10" 

    server.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y openvpn easy-rsa

      mkdir -p /root/.ssh
      cp /home/vagrant/.ssh/auth* /root/.ssh/

    SHELL

    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/provision.yml"
      ansible.inventory_path = "ansible/hosts"
      ansible.host_key_checking = false
      ansible.limit = "all"
    end
  end
end
